E4BIGSCHOOL/Controllers/CoursesController.cs
using E4BIGSCHOOL.Models;
using E4BIGSCHOOL.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E4BIGSCHOOL.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context; 
        
        public CoursesController() { 
            _context = new ApplicationDbContext();
        }
            
        // GET: Courses
       
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel()
            {
                Categories = _context.Categories.ToList()
            };
            return View(viewModel);
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _context.Categories.ToList();
                return View("Create", model);
            }

            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                Date = model.GetDateTime(),
                CategoryId = model.Category,
                Place = model.Place
            };

            _context.Courses.Add(course);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }

        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();

            var courses = _context.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(a => a.Lecturer)
                .Include(l => l.Category)
                .ToList();

            var viewModel = new CourseViewModel
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View (viewModel);
        }
    }
}

E4BIGSCHOOL/Views/Courses/Attending.cshtml
@model E4BIGSCHOOL.ViewModels.CourseViewModel

@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<main>
    <div class="row">
        <ul class="course">
            @foreach (var course in Model.UpcommingCourses)

            {
                <li>
                    <div class="date">
                        <div class="month">
                            @course.Date.ToString("MM")
                        </div>
                        <div class="day">
                            @course.Date.ToString("dd")
                        </div>
                    </div>
                    <div class="detail">
                        <span class="lecturer">
                            @course.Lecturer.Name
                            @if (Model.ShowAction)
                            {
                                <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.LecturerId">
                                    Following
                                </button>
                            }
                        </span>
                        <span class="category">
                            @course.Category.Name
                            @if (Model.ShowAction)
                            {
                                <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">
                                    Going?
                                </button>
                            }

                        </span>
                    </div>

                </li>
            }
        </ul>
    </div>
</main>



@section scripts{

    <script>
        $(document).ready(function () {
            $(".js-toggle-attendance").click(function (e) {
                var button = $(e.target);
                $.post("/api/attendances", { courseId: button.attr("data-course-id") })
                    .done(function () {
                        button
                            .removeClass("btn-default")
                            .addClass("btn-info")
                            .text("Going");
                    })
                    .fail(function () {
                        alert("Something failed");
                    });
            });

            $(".js-toggle-follow").click(function (e) {
                var button = $(e.target);

                $.post("/api/followings", { followeeId: button.attr("data-user-id") })
                    .done(function () {
                        button.text("Following");
                    })
                    .fail(function () {
                        alert("Something failed");
                    });
            });


        });


    </script>

}

E4BIGSCHOOL/Views/Courses/Create.cshtml
@model E4BIGSCHOOL.ViewModels.CourseViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Courses"))
{
    @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Place)
            @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Place)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Time)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Category)
            @Html.DropDownListFor(m => m.Category, 
                 new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Category)
        </div>

        <button type="submit" value="Save" class="btn btn-primary">Save</button>
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");    
}